### PR TITLE
fix: bundle install msg

### LINKED ISSUE #2: MsgInstallBundle does not work
## Relevant Code: 
- `src/lib/messageBuilder.ts`
- `src/contexts/wallet.tsx` for stargateClient setup
- `src/App.tsx` for form/message submission 

### 1. Top Level `/agoric.swingset.MsgInstallBundle`, encoded to Unit8Array

```js
export const makeInstallBundleMsg = ({
  bundle,
  submitter,
}: MsgInstallArgs) => ({
  typeUrl: "/agoric.swingset.MsgInstallBundle",
  value: Uint8Array.from(
    MsgInstallBundle.encode(
      MsgInstallBundle.fromPartial({
        bundle,
        submitter: fromBech32(submitter).data,
      })
    ).finish()
  ),
});
```
Results in:
```bash
Error: Broadcasting transaction failed with code 7 (codespace: sdk). Log: Submitter address cannot be empty: invalid address
```

###  2. Top level `/agoric.swingset.MsgInstallBundle`, with bundle as just a string.

A la https://github.com/Agoric/agoric-sdk/blob/94c6b3c83a5326594f1e2886ae01d6a703a7a68f/packages/agoric-cli/src/publish.js#L270-L281

```js
export const makeInstallBundleMsg = ({ bundle, submitter }: MsgInstallArgs) => ({
  typeUrl: "/agoric.swingset.MsgInstallBundle",
  value: {
    bundle,
    submitter: fromBech32(submitter).data,
  },
});
```

Results in 400 Bad Request:
```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32600,
    "message": "Invalid Request",
    "data": "error reading request body: http: request body too large"
  }
}
```

### 3. Wrapping in `/cosmos.tx.v1beta1.TxBody` , or `/cosmos.tx.v1beta1.Tx`. 

```js
import { Tx, TxBody } from "cosmjs-types/cosmos/tx/v1beta1/tx";
import Long from "long";

...

export const registry = new Registry([
  ...defaultRegistryTypes,
  // ["/cosmos.tx.v1beta1.Tx", Tx],
  // ["/cosmos.tx.v1beta1.TxBody", TxBody],
  ["/agoric.swingset.MsgInstallBundle", MsgInstallBundle],
]);

... 

export const makeInstallBundleMsg = ({ bundle, submitter }: MsgInstallArgs) => ({
  typeUrl: "/cosmos.tx.v1beta1.TxBody",
  value: {
    content: TxBody.encode({
      messages: [
        Any.fromPartial({
          typeUrl: "/agoric.swingset.MsgInstallBundle",
          value: Uint8Array.from(
            MsgInstallBundle.encode(
              MsgInstallBundle.fromPartial({
                bundle,
                submitter: fromBech32(submitter).data,
              })
            ).finish()
          ),
        }),
      ],
      memo: "",
      timeoutHeight: Long.fromNumber(99999999),
      extensionOptions: [],
      nonCriticalExtensionOptions: [],
    }).finish(),
  },
});
```

Don't have a log handy atm, but was running into 'not found in registry' errors for this. I am not sure how to define `MsgInstallBundle` as a child of `Tx` or `TxBody`.

### PR DESCRIPTION
**Pull request by 0xpatrickdev**
-fix: bundle install msg 
- uses compressedBundle (Unit8Array) and uncompressedSize (string) instead of bundle for MsgInstallBundle
- updates @agoric/cosmic-proto via patch-package to include new compressBundle proto
- does not use MsgInstallBundle.(encode|partial), as this results in 'Submitter address cannot be empty' error
- adds compression logic for bundles, h/t @dckc https://gist.github.com/dckc/5eb31c216f4bf10e8f7a0ff82ced6108#file-unbundle-js

- closes #2

### CODE REVIEW

File: src/lib/compression.ts [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+  return new Promise((resolve, reject) => {
+    const reader = new FileReader();
+    reader.onloadend = function () {
+      const base64data = (reader.result as string).split(",")[1];
+      resolve(base64data);
+    };
+    reader.onerror = reject;
+    reader.readAsDataURL(blob);
+  });
+};
```
Comment (0xpatrickdev) [inline src/lib/compression.ts:21]: not currently used, but may be needed for amino encoding
